CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17

SRC = main.cpp Data.cpp Sample.cpp FeatureVector.cpp Knn.cpp KnnCosine.cpp
OBJ = $(SRC:.cpp=.o)

EXEC = main

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CXX) $(OBJ) -o $(EXEC)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<

clean:
	rm -f $(OBJ) $(EXEC)
